export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS'
export const UPLOAD_FAILURE = 'UPLOAD_FAILURE'
export const UPLOAD_REQUEST = 'UPLOAD_REQUEST'

export const READ_START = 'READ_START'
export const READ_SUCCESS = 'READ_SUCCESS'
export const READ_FAILURE = 'READ_FAILURE'

export const RESET_MESSAGE = 'RESET_MESSAGE'

export const FETCH_FAILURE = 'FETCH_FAILURE'
export const FETCH_REQUEST = 'FETCH_REQUEST'
export const FETCH_SUCCESS = 'FETCH_SUCCESS'
