export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS'
export const UPLOAD_FAILURE = 'UPLOAD_FAILURE'
export const UPLOAD_REQUEST = 'UPLOAD_REQUEST'

export const READ_FILE_START = 'READ_FILE_START'
export const READ_FILE_SUCCESS = 'READ_FILE_SUCCESS'
export const READ_FILE_FAILURE = 'READ_FILE_FAILURE'

export const RESET_MESSAGE = 'RESET_MESSAGE'
